### ISSUE TITLE
Short PHP tags should not be used

### ISSUE THREAD

**Issue by amityweb** [speercy/ee-random-string#1]
Hi. You have short PHP tags in your code, so some servers (like mine!) dont support this. It has to be enabled. Whereas all servers support <?php, so I dont think you should use short tags, I got errors and took me a while to find out the issue. Apart from that a nice simple plugin I need to use to set a random session string.

**Comment by speercy** [comment]
Just got around to updating this. Sorry it took so incredibly long (!). As you can tell by my commit history, I'm not on GitHub often and I didn't see this until today.

**Comment by amityweb** [comment]
Ha ha, wow! I have no memory of it was so long ago! No probs, easy change for us at the time, but great your listening! :)
